name: 'Copilot Usage Report'
description: 'Export Copilot usage for an Organization to CSV'
branding:
  icon: 'download'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: true
  csv_path:
    description: 'CSV File path'
    required: true
runs:
  using: 'node16'
  main: 'app/index.js'
